export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const LOAD_CARDS = "LOAD_CARDS";
export const LOAD_CARDS_FAILED = "LOAD_CARDS_FAILED";
export const LOAD_CARDS_LOADING = "LOAD_CARDS_LOADING";

export const BLOG_CARDS = "BLOG_CARDS";
export const BLOG_CARDS_FAILED = "BLOG_CARDS_FAILED";
export const BLOG_CARDS_LOADING = "BLOG_CARDS_LOADING";

export const LOAD_BESTLEADER = "LOAD_BESTLEADER";
export const LOAD_BESTLEADER_FAILED = "LOAD_BESTLEADER_FAILED";
export const LOAD_BESTLEADER_LOADING = "LOAD_BESTLEADER_LOADING";

export const LOADING_PUT_DATA = "LOADING_PUT_DATA";
export const PUT_DATA = "PUT_DATA";
export const PUT_DATA_FAILED = "PUT_DATA_FAILED";

export const START_CREATE_TRIP = "START_CREATE_TRIP";
export const POST_TRIP_DATA = "POST_TRIP_DATA";
export const POST_TRIP_DATA_FAILED = "POST_TRIP_DATA_FAILED";
